spring:
  datasource:
    url: jdbc:mysql://192.168.72.134/spring_cache?characterEncoding=utf8&useSSL=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    tomcat:
      max-active: 1000
      max-idle: 1000


